token: MEV_CI_DOCS
label: component-ci-nodes
dockerImage: ubuntu:latest

scmCheckoutStrategies: 
  - strategy-name: custom-checkout
    checkout-script-name: jenkins/custom-checkout.sh
  # - strategy-name: default
  # - strategy-name: repo-tool-with-gh-token
  #   repo-manifest-url: https://github.com/Brandonawan/shared-library.git
  #   repo-manifest-branch: main
  #   github-token-jenkins-credential-id: Brandon-token
  #   repo-manifest-group: IDPF
    
  # - strategy-name: custom-checkout
  #   checkout-script-name: jenkins/custom-checkout.sh
  
# dockerImage: artifacts-bxdsw.sc.intel.com:9444/mev/fedora:30

# jenkinsFileEath: ienkinsilenkinsfile-post-merge

#location of jenkins build script (optional)

# scriptPath: jenkins

# how to get the code necessary for the build
#scmCheckoutStrategy: -

# supported values [scm-checkout:strategy(default), repo-tool-with-gh-token-strategy, custom:scm:checkout:strateay]
# scmCheckoutStrateay:
# - strategy-name: repo-tool-with-gh-token:sirategy.
#   github-token-ienkins-credential-id: afadfadfadfdaf
#   repo-manifest-url: github.comy/intel-innersource/networking.ipu. mountevans.manifests
#   repo-manifest-branch: mev-truck:idpf-test
#   repo-manifest-group: IDPF

# scmCheckoutStrateay:
# - strategy-name: custom:scm-checkout:strategy
# - checkout-script-name: jenkins-checkout

# scmCheckoutStrateay:
# - strategy-name: scm:checkout-strateay

# docker image url (required)

dockermage: artifacts-bxdsw.sc.intel.com:9444/mevirocky:9.2
# github trigger token (required)
#githubTrigagerToken: bxd_migration
token: bxd_migration

# jenkins node pool label (optional)

Iabel: component-ci-nodes

# dockerImage: ubuntu:latest

