#!/bin/bash

# This script is part of the Jenkins shared library.
# It reads configuration from pipeline-config.yml and performs some actions.

# Get the absolute path to the directory containing this script
scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Specify the relative path to the YAML file
yamlFile="${scriptDir}/pipeline-config.yml"

# Load the YAML file and assign variables
if [ -f "$yamlFile" ]; then
    eval $(cat "$yamlFile" | sed 's/:[^:\/\/]/="/;s/$/"/')
else
    echo "Error: $yamlFile not found."
    exit 1
fi

# Use the values in your script
echo "Running jenkin-build script..."
echo "Docker Image: $dockerImage"
echo "Token: $token"
echo "Label: $label"
